### PR TITLE
Farbe und Bunt und so!

### PR DESCRIPTION
**Pull request by Drezil**

### CODE REVIEW

**Comment by jbetzend** [comment]
Does this make the program require stack or just give it the capacity to be build with it?
Either way I'm disinclined to merge PRs (that I will have to support) as long as I'm not familiar

**Comment by Drezil** [comment]
It just gives it the capability to build with it. You can do still a cabal build if you prefer.
And with stack there is no maintenance needed as all package versions are fixed through the lts-buildplan.

**Comment by jbetzend** [comment]
Maintenance ≠ Support 
A user might come to me and ask how to build this with stack or that they have problems with it. Since it's in the program I would feel obligated (but unable) to help them.
Would you consider a PR with only the latex colour changes?

**Comment by Drezil** [comment]
you can merge now.

**Pull request merged**
